### ISSUE TITLE
ClickFolder(item) - Couldn't find element

### ISSUE THREAD

**Issue by isaquerochak** [totvs/tir-script-samples#1]
Estou executando o teste test_MATA030_CT001. É apresentado mensagem de aguardando elemento, e mesmo com a pagina carregada o elemento não é encontrado.

 self.oHelper.ClickFolder('Cadastrais')

24/09/2018 13:58 |   | TI03| MATA030 | 24/09/2018 13:57 | 1 | 0 | 1 | 42.49 | 12 | 12.1.017 | CT001 - Couldn't find element |

**Comment by renanllisboa** [comment]
Boa tarde, poderia nos encaminhar um print da tela que está executando o script?

Atenciosamente

**Comment by isaquerochak** [comment]
Segue abaixo,
OBS: Print gerado pela ferramenta.

![error](https://user-images.githubusercontent.com/19375217/45968684-0a4eae00-c008-11e8-8e74-ab6ca5e322ae.png)

**Comment by renanllisboa** [comment]
@isaquerochak , poderia nos disponibilizar mais algumas informações?

- Browser utilizado
- Versão do Browser
- Versão do Webapp
- Build do Protheus(13 ou 17 / x32 ou x64)

Se possível faz um teste com outra aba para ver se também reproduz o problema.

Atenciosamente

**Comment by isaquerochak** [comment]
Browser utilizado : Firefox
Versão do Browser : 62.0.2 (64-bit)
Versão do Webapp : SmartClient WebApp versão 4.2.0 - Build 7.00.131227A
Build do Protheus(13 ou 17 / x32 ou x64) : 12.1.017 x32
mozilla/geckodriver: v0.22.0

Testei com a aba 'Adm/fin.', também sem sucesso.
`self.oHelper.ClickFolder('Adm/fin.')`

**Comment by renanllisboa** [comment]
@isaquerochak, uma outra dúvida, seu server está no Linux?

**Comment by isaquerochak** [comment]
Windows Server 2012

**Comment by renanllisboa** [comment]
A versão do webapp você baixou do portal do cliente?

**Comment by renanllisboa** [comment]
@isaquerochak fizemos testes com as mesmas configurações que você está utilizando e não conseguimos reproduzir o problema. Porem reproduzimos essa inconsistência apenas no "Chrome". 

Fizemos pequenos ajustes e conseguimos executar o script até o final com sucesso.

Favor atualizar com a nova Master e nos informe se houve alguma mudança no comportamento.

**Comment by isaquerochak** [comment]
> A versão do webapp você baixou do portal do cliente?

Sim

**Comment by isaquerochak** [comment]
> @isaquerochak fizemos testes com as mesmas configurações que você está utilizando e não conseguimos reproduzir o problema. Porem reproduzimos essa inconsistência apenas no "Chrome".
> 
> Fizemos pequenos ajustes e conseguimos executar o script até o final com sucesso.
> 
> Favor atualizar com a nova Master e nos informe se houve alguma mudança no comportamento.

Resolvido, funcionando perfeitamente agora.

**Comment by isaquerochak** [comment]
> @isaquerochak fizemos testes com as mesmas configurações que você está utilizando e não conseguimos reproduzir o problema. Porem reproduzimos essa inconsistência apenas no "Chrome".
> 
> Fizemos pequenos ajustes e conseguimos executar o script até o final com sucesso.
> 
> Favor atualizar com a nova Master e nos informe se houve alguma mudança no comportamento.

Resolvido, funcionando perfeitamente agora.
