### ISSUE TITLE
TIR - ModuleNotFoundError: No module named 'tir'

### ISSUE THREAD

**Issue by allanfreiresa** [totvs/tir-script-samples#2]
Bom dia!

Alguém poderia me ajudar com este erro, ao executar:

Erro ao tentar implementar o TIR. Lembrando que conforme Vídeo do Webinar os programas precisam estar todos juntos, todos os detalhes estão em anexo:

ModuleNotFoundError: No module named 'tir'
[tir-script-samples (1).zip](https://github.com/totvs/tir-script-samples/files/3680957/tir-script-samples.1.zip)

File "c:\Users\allan_freire\PycharmProjects\tir-script-samples\MATA030TESTCASE.py", line 1, in <module>
from tir import Webapp
ModuleNotFoundError: No module named 'tir'
PS C:\Users\allan_freire\PycharmProjects\tir-script-samples>

Muito obrigado, 

Allan Freire
ASUS BRASIL

**Comment by renanllisboa** [comment]
Bom dia, Allan.

Só lembrando que temos uma canal direcionado para dúvidas sobre instalação e usabilidade do TIR, em outro momento pode nos mandar sua dúvida por esse canal, segue endereço:

https://gitter.im/totvs-tir/General

Este erro é devido ao pacote não estar instalado, isso pode ocorrer no momento da instalação até mesmo pelo instalador, se ele não conseguiu as permissões para efetivar a cópia dos arquivos.

Você pode tentar reinstalar o pacote através do comando:
 "pip install git+https://github.com/totvs/tir.git --upgrade".

Ao efetivar a instalação do pacote os arquivos são encontrados na pasta:
"C:\Python37\Lib\site-packages" ou em outro caminho de instalação nessa mesma estrutura, dentro da pasta "site-packages" deve constar a pasta "tir".

Você também pode confirmar a instação do TIR executando o comando no prompt: "pip show tir"

Qualquer dúvida, pode me chamar.

Atenciosamente

**Comment by allanfreiresa** [comment]
Renan,

Obrigado pelo retorno. Já estou utlizando este canal, muto bom por sinal,
já estou desenvolvendo scripts para outros cadastros.

No momento estou com um pouco de dificuldade de fazer as funções de
alteração e exclusão para cada cadastro.

De qualquer forma, vocês estão de parabéns por essa novidade,  Não
desenvolvo em python mas vou começar a aprender.

Att.



Em qua, 2 de out de 2019 às 09:48, Renan Lacerda Lisboa <
notifications@github.com> escreveu:
